// M5-ctOS localization - English only
#define TXT_BACK "Back"
#define TXT_SETTINGS "Settings"
#define TXT_NEVER "Never"
#define TXT_SEC "seconds"
#define TXT_MIN "minutes"
#define TXT_AUTO_DIM "SET AUTO DIM TIME"
#define TXT_SET_BRIGHT "SET BRIGHTNESS"
#define TXT_BATT_INFO "Battery Info"
#define TXT_BRIGHT "Brightness"
#define TXT_ABOUT "About"
#define TXT_REBOOT "Reboot"
#define TXT_CLR_SETTINGS "Clear Settings"
#define TXT_CLRING_SETTINGS "Restoring Default\nSettings..."
#define TXT_EXIT "Press any key to exit"
#define TXT_ADV "Advertising:\n"
#define TXT_SP_RND "Swift Pair Random"
#define TXT_SEL_EXIT2 "\n\nNext: Exit"
#define TXT_SA_CRASH "SourApple Crash"
#define TXT_CMB_BT_SPAM " Combined BT Spam"
#define TXT_AD_SPAM "Android Spam"
#define TXT_AJ_TRANSF_NM "Transfer Number"
#define TXT_AJ_TV_COLOR "TV Color Balance"
#define TXT_STP_NW_PH "Setup New Phone"
#define TXT_SA_ADV "SourApple Advertisement: "
#define TXT_SP_ADV "SwiftPair Advertisement: '%s' - "
#define TXT_AD_SPAM_ADV "Android Spam Advertisement: "
#define TXT_AJ_ADV "AppleJuice Advertisement: "
#define TXT_INST_NXT "Next: Down Arrow"
#define TXT_INST_PRV "Prev: Up Arrow"
#define TXT_INST_SEL "Sel : Enter or ->"
#define TXT_INST_HOME "Home: Esc   or <- "
#define TXT_INST_PRSS_KEY "         Press a key"
#define TXT_BLACK "Black"
#define TXT_NAVY "Navy"
#define TXT_DARKGREEN "Dark Green"
#define TXT_DARKCYAN "Dark Cyan"
#define TXT_MAROON "Maroon"
#define TXT_PURPLE "Purple"
#define TXT_OLIVE "Olive"
#define TXT_LIGHTGREY "Light Grey"
#define TXT_DARKGREY "Dark Grey"
#define TXT_BLUE "Blue"
#define TXT_GREEN "Green"
#define TXT_CYAN "Cyan"
#define TXT_RED "Red"
#define TXT_MAGENTA "Magenta"
#define TXT_YELLOW "Yellow"
#define TXT_WHITE "White"
#define TXT_ORANGE "Orange"
#define TXT_GREENYELLOW "Green Yellow"
#define TXT_PINK "Pink"
#define TXT_COLOR "Custom Colors"
#define TXT_SET_FGCOLOR "MAIN COLOR"
#define TXT_SET_BGCOLOR "BACKGROUND COLOR"
#define TXT_THEME "Color Theme"
